// Generated by ts-to-zod
import { z } from 'zod';

export const tokenRequestSchema = z.object({
    clientId: z.string(),
    clientSecret: z.string(),
});

export const tokenResponseSchema = z.object({
    token: z.string(),
    expiresAt: z.string(),
});
