// Comprehensive cricket team to ISO country code mapping
// Based on ICC members and uses ISO 3166-1 alpha-2 country codes
export const cricketTeamMapping = new Map<string, string>([
  // ICC Full Members
  ['Afghanistan', 'af'],
  ['Australia', 'au'],
  ['Bangladesh', 'bd'],
  ['England', 'gb'],
  ['India', 'in'],
  ['Ireland', 'ie'],
  ['New Zealand', 'nz'],
  ['Pakistan', 'pk'],
  ['South Africa', 'za'],
  ['Sri Lanka', 'lk'],
  ['West Indies', 'ag'],  // Using Antigua & Barbuda as representative
  ['Zimbabwe', 'zw'],

  // ICC Associate Members with frequent appearances
  ['Scotland', 'gb-sct'],
  ['Netherlands', 'nl'],
  ['Nepal', 'np'],
  ['Oman', 'om'],
  ['United Arab Emirates', 'ae'],
  ['Hong Kong', 'hk'],
  ['Canada', 'ca'],
  ['USA', 'us'],
  ['United States', 'us'],
  ['Papua New Guinea', 'pg'],
  ['Namibia', 'na'],
  ['Kenya', 'ke'],
  ['Uganda', 'ug'],
  ['Jersey', 'je'],
  ['Guernsey', 'gg'],
  ['Malaysia', 'my'],
  ['Singapore', 'sg'],
  ['Thailand', 'th'],
  ['Kuwait', 'kw'],
  ['Qatar', 'qa'],
  ['Bahrain', 'bh'],
  ['Bermuda', 'bm'],
  ['Cayman Islands', 'ky'],
  ['Denmark', 'dk'],
  ['Germany', 'de'],
  ['Italy', 'it'],
  ['France', 'fr'],
  ['Norway', 'no'],
  ['Sweden', 'se'],
  ['Austria', 'at'],
  ['Belgium', 'be'],
  ['Spain', 'es'],
  ['Portugal', 'pt'],
  ['Czech Republic', 'cz'],
  ['Finland', 'fi'],
  ['Estonia', 'ee'],
  ['Latvia', 'lv'],
  ['Lithuania', 'lt'],
  ['Poland', 'pl'],
  ['Brazil', 'br'],
  ['Argentina', 'ar'],
  ['Chile', 'cl'],
  ['Mexico', 'mx'],
  ['Peru', 'pe'],
  ['Japan', 'jp'],
  ['China', 'cn'],
  ['South Korea', 'kr'],
  ['Indonesia', 'id'],
  ['Philippines', 'ph'],
  ['Vietnam', 'vn'],
  ['Cambodia', 'kh'],
  ['Laos', 'la'],
  ['Myanmar', 'mm'],
  ['Israel', 'il'],
  ['Turkey', 'tr'],
  ['Greece', 'gr'],
  ['Cyprus', 'cy'],
  ['Malta', 'mt'],
  ['Gibraltar', 'gi'],
  ['Isle of Man', 'im'],
  ['Fiji', 'fj'],
  ['Vanuatu', 'vu'],
  ['Cook Islands', 'ck'],
  ['Samoa', 'ws'],
  ['Tanzania', 'tz'],
  ['Botswana', 'bw'],
  ['Ghana', 'gh'],
  ['Nigeria', 'ng'],
  ['Gambia', 'gm'],
  ['Sierra Leone', 'sl'],
  ['Rwanda', 'rw'],
  ['Malawi', 'mw'],
  ['Mozambique', 'mz'],
  ['Lesotho', 'ls'],
  ['Eswatini', 'sz'],
  ['Hungary', 'hu'],

  // Alternative/common name variations
  ['UAE', 'ae'],
  ['United States of America', 'us'],
  ['UK', 'gb'],
  ['Britain', 'gb'],
  ['Great Britain', 'gb'],
  ['Northern Ireland', 'gb'],
  ['Wales', 'gb'],
  ['Windies', 'ag'],
  ['WI', 'ag'],
  ['West Indies Cricket Team', 'ag'],
  ['South Korea', 'kr'],
  ['Republic of Korea', 'kr'],
  ['North Korea', 'kp'],
  ['Democratic Republic of Congo', 'cd'],
  ['Congo', 'cg'],
  ['Czech', 'cz'],
  ['Holland', 'nl'],
  ['Burma', 'mm'],
]);

// Special cases for common team name abbreviations
export const specialTeamCases = new Map<string, string>([
  ['eng', 'gb'],
  ['aus', 'au'],
  ['ind', 'in'],
  ['aut', 'at'],
  ['pak', 'pk'],
  ['sa', 'za'],
  ['rsa', 'za'],
  ['nz', 'nz'],
  ['ban', 'bd'],
  ['sl', 'lk'],
  ['afg', 'af'],
  ['ire', 'ie'],
  ['zim', 'zw'],
  ['wi', 'ag'],
  ['sco', 'gb-sct'],
  ['ned', 'nl'],
  ['nep', 'np'],
  ['oma', 'om'],
  ['png', 'pg'],
  ['nam', 'na'],
  ['ken', 'ke'],
  ['uga', 'ug'],
]); 