// Generated by ts-to-zod
import { z } from 'zod';

const matchIdSchema = z.string().regex(/^[a-zA-Z0-9]{16}$/);

export const matchStatsParamsSchema = z.object({
    matchId: matchIdSchema,
});

export const liveMatchesResponseSchema = z.object({
    matchUrl: z.string().optional(),
    matchName: z.string().optional(),
    matchId: matchIdSchema.optional(),
});

export const iPreviousInningsSchema = z.object({
    score: z.string(),
    wickets: z.string(),
});

export const iTeamDataSchema = z.object({
    isBatting: z.boolean(),
    name: z.string(),
    score: z.string(),
    overs: z.string().optional(),
    wickets: z.string(),
    previousInnings: iPreviousInningsSchema.optional(),
});

export const playerDataSchema = z.object({
    name: z.string(),
    runs: z.string(),
    balls: z.string(),
});

export const runRateDataSchema = z.object({
    currentRunRate: z.number(),
    requiredRunRate: z.number(),
});

export const commentaryDataSchema = z.object({
    over: z.string().optional(),
    commentary: z.string(),
    hasOver: z.boolean(),
});

export const matchStatsResponseSchema = z.object({
    matchId: matchIdSchema,
    isLive: z.boolean().optional(),
    team1: iTeamDataSchema,
    team2: iTeamDataSchema,
    onBatting: z.object({
        player1: playerDataSchema,
        player2: playerDataSchema,
    }),
    runRate: runRateDataSchema.optional(),
    summary: z.string(),
    tournamentName: z.string().optional(),
    matchName: z.string().optional(),
});
